### ISSUE TITLE
correct fonts for navigation

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/wwc#8]

**Comment by jalbertbowden** [comment]
i went with  mdcn medium because md seems like my css was making it break lines. a lot. it does automatically when i swap them out:
<img width="368" alt="screen shot 2016-06-19 at 9 47 24 pm" src="https://cloud.githubusercontent.com/assets/46432/16181317/ab875fa6-3667-11e6-96ec-59b89af232b3.png">
setting: <code>letter-spacing:-2px</code> makes it better i think:
<img width="275" alt="screen shot 2016-06-19 at 9 47 59 pm" src="https://cloud.githubusercontent.com/assets/46432/16181326/c706aed0-3667-11e6-8482-93c2b605282a.png">
but also maybe to bold?
